version: "3"
services:

  db:
    restart: always
    image: mysql:5.7
    container_name: my_db
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - back
    environment:
      MYSQL_ROOT_PASSWORD: admin@123
    ports:
      - "3306:3306"

networks:
  back:
    driver: bridge

volumes:
  mysql:





